# question.py — A single interview question within a session
# generated by LangChain/Ollama at session start (or dynamically)
from sqlalchemy import Column, Integer, String, Text, ForeignKey, Boolean
from sqlalchemy.orm import relationship
from app.db.database import Base


class Question(Base):
    __tablename__ = "questions"

    id = Column(Integer, primary_key=True, index=True)

    # fk to interview_sessions — this question belongs to one session
    session_id = Column(Integer, ForeignKey("interview_sessions.id"), nullable=False, index=True)

    # actual quest text 
    question_text = Column(Text, nullable=False)

    # positoon of ques in the session
    order_index = Column(Integer, nullable=False, default=0)

    # type
    question_type = Column(String, default="technical", nullable=False)

    # folloup of pev ques-> gen by ai
    is_follow_up = Column(Boolean, default=False, nullable=False)

    session = relationship("InterviewSession", back_populates="questions")

    # 1 ques -> m ans
    answers = relationship(
        "Answer",
        back_populates="question",
        cascade="all, delete-orphan",
    )

    def __repr__(self):
        return f"<Question id={self.id} session_id={self.session_id} order={self.order_index}>"